/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Name = IDL.Text;
export const Response = IDL.Text;

export const idlService = IDL.Service({
  'checkResponse' : IDL.Func([], [IDL.Bool], ['query']),
  'submitResponse' : IDL.Func([Name, Response], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Name = IDL.Text;
  const Response = IDL.Text;
  
  return IDL.Service({
    'checkResponse' : IDL.Func([], [IDL.Bool], ['query']),
    'submitResponse' : IDL.Func([Name, Response], [], []),
  });
};

export const init = ({ IDL }) => { return []; };